security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN:
            ## CATEGORY
            - ROLE_KING_ADMIN_CATEGORY_CREATE
            - ROLE_KING_ADMIN_CATEGORY_EDIT
            - ROLE_KING_ADMIN_CATEGORY_VIEW
            - ROLE_KING_ADMIN_CATEGORY_LIST
            ## CATEGORY INSTANCE
            - ROLE_KING_ADMIN_CATEGORY_INSTANCE_CREATE
            - ROLE_KING_ADMIN_CATEGORY_INSTANCE_LIST
            - ROLE_KING_ADMIN_CATEGORY_INSTANCE_EDIT
            - ROLE_KING_ADMIN_CATEGORY_INSTANCE_VIEW
            ## ICON
            - ROLE_KING_ADMIN_ICON_CREATE
            - ROLE_KING_ADMIN_ICON_EDIT
            - ROLE_KING_ADMIN_ICON_VIEW
            - ROLE_KING_ADMIN_ICON_LIST
            ## INTEREST
            - ROLE_KING_ADMIN_INTEREST_EDIT
            - ROLE_KING_ADMIN_INTEREST_VIEW
            - ROLE_KING_ADMIN_INTEREST_LIST
            ## USER
            - ROLE_USER_ADMIN_USER_LIST
            - ROLE_USER_ADMIN_USER_VIEW
            - ROLE_USER_ADMIN_USER_CREATE
            - ROLE_USER_ADMIN_USER_EDIT
            #- ROLE_USER_ADMIN_USER_DELETE
            - ROLE_USER_ADMIN_USER_EXPORT
            - ROLE_CLIENT

        #ROLE_ADMIN:  [ROLE_CLIENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory:
            memory: ~
            
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:  ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        main:
            anonymous: ~
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/register, role: ROLE_CLIENT }
