king_homepage:
    path:     /
    defaults: { _controller: KingBundle:Default:search }
    
king_all_result:
    path:  /all-result/{categoryInstanceId}
    defaults: { _controller: KingBundle:Default:allResult }
    
king_register_interest:
    path:    /register
    defaults: { _controller: KingBundle:Default:registerInterest }
    
king_result:
    path:  /result
    defaults: { _controller: KingBundle:Default:result }
    
king_interest_detail:
    path: /interest-detail/{interestId}
    defaults: { _controller: KingBundle:Default:interestDetail }

king_one_result:
    path:  /oneResult
    defaults: { _controller: KingBundle:Default:oneResult }

king_video_result:
    path:  /videoResult
    defaults: { _controller: KingBundle:Default:videoResult }
    
king_search:
    path:  /wonsano-search
    defaults: { _controller: KingBundle:Default:search }
    
king_search_content:
    path:  /wonsano-search-content
    defaults: { _controller: KingBundle:Default:searchContent }

king_icon_ajax_content:
    path:  /icon-ajax
    defaults: { _controller: KingBundle:Default:iconAjax }
    

