king_homepage:
    path:     /
    defaults: { _controller: KingBundle:Default:index }
    
king_register_interest:
    path:    /register
    defaults: { _controller: KingBundle:Default:registerInterest }
    
king_result:
    path:  /result
    defaults: { _controller: KingBundle:Default:result }

king_one_result:
    path:  /oneResult
    defaults: { _controller: KingBundle:Default:oneResult }

king_video_result:
    path:  /videoResult
    defaults: { _controller: KingBundle:Default:videoResult }
    

