<?php

namespace KingBundle\Repository;

/**
 * CategoryInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
