<?php

namespace KingBundle\Repository;

/**
 * CategoryInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryInstanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getForSearch($keyWord)
    {
        $query = $this->_em->createQueryBuilder();
                 $query->select('c')
                    ->from('KingBundle:CategoryInstance', 'c')
                    ->where($query->expr()->like('c.name', $query->expr()->literal('%' . $keyWord . '%')))
                    ->orderBy('c.name', 'ASC')
                    ->getQuery()
                    ->setParameter('keyWord', '%'.$keyWord.'%');
              
        return $query->getQuery()->getResult();
    }
}
